/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;
import Utils.Session;

/**
 *
 * @author Tester
 */
public class PPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PPrincipal
     */
    public PPrincipal() {
        initComponents();
        if(Session.user_type != 0) {
           menuMantenimiento.setVisible(false);
        }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuMantenimiento = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        saveMenuItem2 = new javax.swing.JMenuItem();
        saveMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        exitMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuMantenimiento.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tester\\Desktop\\form.png")); // NOI18N
        menuMantenimiento.setMnemonic('f');
        menuMantenimiento.setText("Mantenimientos");

        saveMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tester\\Desktop\\curso.png")); // NOI18N
        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Cursos");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        menuMantenimiento.add(saveMenuItem);

        exitMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tester\\Desktop\\close_big.png")); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        menuMantenimiento.add(exitMenuItem);

        menuBar.add(menuMantenimiento);
        menuMantenimiento.getAccessibleContext().setAccessibleName("MenuMantenimientos");

        jMenu1.setText("Cursos");

        saveMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tester\\Desktop\\curso.png")); // NOI18N
        saveMenuItem2.setMnemonic('s');
        saveMenuItem2.setText("Mis Cursos");
        saveMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenuItem2);

        saveMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tester\\Desktop\\curso.png")); // NOI18N
        saveMenuItem1.setMnemonic('s');
        saveMenuItem1.setText("Tomar un Nuevo Curso");
        saveMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenuItem1);

        menuBar.add(jMenu1);

        jMenu2.setText("Salir");

        exitMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tester\\Desktop\\close_big.png")); // NOI18N
        exitMenuItem1.setMnemonic('x');
        exitMenuItem1.setText("Exit");
        exitMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(exitMenuItem1);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
        PCurso doform = new PCurso();
        desktopPane.add(doform);
        doform.toFront();
        doform.setVisible(true);
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void saveMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem1ActionPerformed
        // TODO add your handling code here:
        FrmTakeNewCourse doform = new FrmTakeNewCourse();
        desktopPane.add(doform);
        doform.toFront();
        doform.setVisible(true);
    }//GEN-LAST:event_saveMenuItem1ActionPerformed

    private void saveMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem2ActionPerformed
        // TODO add your handling code here:
        PMisCursos doform = new PMisCursos();
        desktopPane.add(doform);
        doform.toFront();
        doform.setVisible(true);
        
    }//GEN-LAST:event_saveMenuItem2ActionPerformed

    private void exitMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem exitMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuMantenimiento;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem saveMenuItem1;
    private javax.swing.JMenuItem saveMenuItem2;
    // End of variables declaration//GEN-END:variables

}
